/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MyUser service. Represents a row in the &quot;user_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.amf.registration.model.impl.MyUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.amf.registration.model.impl.MyUserImpl}.
 * </p>
 *
 * @author liferay
 * @see MyUser
 * @see com.amf.registration.model.impl.MyUserImpl
 * @see com.amf.registration.model.impl.MyUserModelImpl
 * @generated
 */
public interface MyUserModel extends BaseModel<MyUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my user model instance should use the {@link MyUser} interface instead.
	 */

	/**
	 * Returns the primary key of this my user.
	 *
	 * @return the primary key of this my user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my user.
	 *
	 * @param primaryKey the primary key of this my user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this my user.
	 *
	 * @return the user ID of this my user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this my user.
	 *
	 * @param userId the user ID of this my user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this my user.
	 *
	 * @return the user uuid of this my user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this my user.
	 *
	 * @param userUuid the user uuid of this my user
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MyUser myUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MyUser> toCacheModel();

	@Override
	public MyUser toEscapedModel();

	@Override
	public MyUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}