/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.amf.registration.service.base;

import com.amf.registration.model.MyUser;
import com.amf.registration.service.MyUserLocalService;
import com.amf.registration.service.persistence.MonitorEventPersistence;
import com.amf.registration.service.persistence.MyUserFinder;
import com.amf.registration.service.persistence.MyUserPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the my user local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.amf.registration.service.impl.MyUserLocalServiceImpl}.
 * </p>
 *
 * @author liferay
 * @see com.amf.registration.service.impl.MyUserLocalServiceImpl
 * @see com.amf.registration.service.MyUserLocalServiceUtil
 * @generated
 */
public abstract class MyUserLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements MyUserLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.amf.registration.service.MyUserLocalServiceUtil} to access the my user local service.
	 */

	/**
	 * Adds the my user to the database. Also notifies the appropriate model listeners.
	 *
	 * @param myUser the my user
	 * @return the my user that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MyUser addMyUser(MyUser myUser) throws SystemException {
		myUser.setNew(true);

		return myUserPersistence.update(myUser);
	}

	/**
	 * Creates a new my user with the primary key. Does not add the my user to the database.
	 *
	 * @param userId the primary key for the new my user
	 * @return the new my user
	 */
	@Override
	public MyUser createMyUser(long userId) {
		return myUserPersistence.create(userId);
	}

	/**
	 * Deletes the my user with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param userId the primary key of the my user
	 * @return the my user that was removed
	 * @throws PortalException if a my user with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MyUser deleteMyUser(long userId)
		throws PortalException, SystemException {
		return myUserPersistence.remove(userId);
	}

	/**
	 * Deletes the my user from the database. Also notifies the appropriate model listeners.
	 *
	 * @param myUser the my user
	 * @return the my user that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MyUser deleteMyUser(MyUser myUser) throws SystemException {
		return myUserPersistence.remove(myUser);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MyUser.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return myUserPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.amf.registration.model.impl.MyUserModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return myUserPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.amf.registration.model.impl.MyUserModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return myUserPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return myUserPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return myUserPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public MyUser fetchMyUser(long userId) throws SystemException {
		return myUserPersistence.fetchByPrimaryKey(userId);
	}

	/**
	 * Returns the my user with the primary key.
	 *
	 * @param userId the primary key of the my user
	 * @return the my user
	 * @throws PortalException if a my user with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public MyUser getMyUser(long userId)
		throws PortalException, SystemException {
		return myUserPersistence.findByPrimaryKey(userId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return myUserPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the my users.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.amf.registration.model.impl.MyUserModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of my users
	 * @param end the upper bound of the range of my users (not inclusive)
	 * @return the range of my users
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<MyUser> getMyUsers(int start, int end)
		throws SystemException {
		return myUserPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of my users.
	 *
	 * @return the number of my users
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getMyUsersCount() throws SystemException {
		return myUserPersistence.countAll();
	}

	/**
	 * Updates the my user in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param myUser the my user
	 * @return the my user that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MyUser updateMyUser(MyUser myUser) throws SystemException {
		return myUserPersistence.update(myUser);
	}

	/**
	 * Returns the monitor event local service.
	 *
	 * @return the monitor event local service
	 */
	public com.amf.registration.service.MonitorEventLocalService getMonitorEventLocalService() {
		return monitorEventLocalService;
	}

	/**
	 * Sets the monitor event local service.
	 *
	 * @param monitorEventLocalService the monitor event local service
	 */
	public void setMonitorEventLocalService(
		com.amf.registration.service.MonitorEventLocalService monitorEventLocalService) {
		this.monitorEventLocalService = monitorEventLocalService;
	}

	/**
	 * Returns the monitor event persistence.
	 *
	 * @return the monitor event persistence
	 */
	public MonitorEventPersistence getMonitorEventPersistence() {
		return monitorEventPersistence;
	}

	/**
	 * Sets the monitor event persistence.
	 *
	 * @param monitorEventPersistence the monitor event persistence
	 */
	public void setMonitorEventPersistence(
		MonitorEventPersistence monitorEventPersistence) {
		this.monitorEventPersistence = monitorEventPersistence;
	}

	/**
	 * Returns the my user local service.
	 *
	 * @return the my user local service
	 */
	public com.amf.registration.service.MyUserLocalService getMyUserLocalService() {
		return myUserLocalService;
	}

	/**
	 * Sets the my user local service.
	 *
	 * @param myUserLocalService the my user local service
	 */
	public void setMyUserLocalService(
		com.amf.registration.service.MyUserLocalService myUserLocalService) {
		this.myUserLocalService = myUserLocalService;
	}

	/**
	 * Returns the my user persistence.
	 *
	 * @return the my user persistence
	 */
	public MyUserPersistence getMyUserPersistence() {
		return myUserPersistence;
	}

	/**
	 * Sets the my user persistence.
	 *
	 * @param myUserPersistence the my user persistence
	 */
	public void setMyUserPersistence(MyUserPersistence myUserPersistence) {
		this.myUserPersistence = myUserPersistence;
	}

	/**
	 * Returns the my user finder.
	 *
	 * @return the my user finder
	 */
	public MyUserFinder getMyUserFinder() {
		return myUserFinder;
	}

	/**
	 * Sets the my user finder.
	 *
	 * @param myUserFinder the my user finder
	 */
	public void setMyUserFinder(MyUserFinder myUserFinder) {
		this.myUserFinder = myUserFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.amf.registration.model.MyUser",
			myUserLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.amf.registration.model.MyUser");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return MyUser.class;
	}

	protected String getModelClassName() {
		return MyUser.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = myUserPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.amf.registration.service.MonitorEventLocalService.class)
	protected com.amf.registration.service.MonitorEventLocalService monitorEventLocalService;
	@BeanReference(type = MonitorEventPersistence.class)
	protected MonitorEventPersistence monitorEventPersistence;
	@BeanReference(type = com.amf.registration.service.MyUserLocalService.class)
	protected com.amf.registration.service.MyUserLocalService myUserLocalService;
	@BeanReference(type = MyUserPersistence.class)
	protected MyUserPersistence myUserPersistence;
	@BeanReference(type = MyUserFinder.class)
	protected MyUserFinder myUserFinder;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private MyUserLocalServiceClpInvoker _clpInvoker = new MyUserLocalServiceClpInvoker();
}